/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package json.rpc.java;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        Integer port = 80;
        //assertNotNull(classUnderTest.listen(port), "app should have a greeting");
    }
}
