/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package json.rpc.java;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.io.IOException;

class AppTest {
    @Test void appHasAGreeting() {
        try {
			App classUnderTest = new App(80);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        Integer port = 80;
        //assertNotNull(classUnderTest.listen(port), "app should have a greeting");
    }
}
